function RadCollisionMatlab(stlpath,gantry,patient,couch,nobj)
% RadCollisionMatlab 
home
addpath(...
    ['.',filesep,'read_binary_stl_file'],...
    ['.',filesep,'aabb-tree'],...
    ['.',filesep,'min-distance-3d-triangles'])

%% Default model
if nargin == 0
    param.stlpath = ['.',filesep,'models',filesep];
    param.Gantry_filename = [param.stlpath,'RotatingHeads.stl'];
    param.Patient_filename = [param.stlpath,'Standardhumanbody170cm.stl'];
    param.Couch_filename = [param.stlpath,'Hexapod.stl'];
    param.nobj=400;
elseif nargin ==5
    param.stlpath = stlpath;
    param.Gantry_filename = [stlpath,gantry];
    param.Patient_filename = [stlpath,patient];
    param.Couch_filename = [stlpath,couch];
    param.nobj=nobj;
else
    error('Only either no arguments, or 5 arguments')
end
%% Main figure
figure(...
    'NumberTitle','off',...
    'Name','Rad Collision Master',...
    'Position',[800   200   800   600],...
    'MenuBar','figure',...
    'Color','white',...
    'Visible','off',...
    'UserData',param);
axes(...
    'Position',[0.3 0.1 0.66 0.86],...
    'clipping','off');
axis equal off
view([-135 35]);
hold on

%% Reference system
c = -600;
d = 300;
quiver3([c c,c],[c c c],[c c c],[-d 0,0],[0  -d 0],[0,0,-d])
text(c-d-25,c,c,'x')
text(c,c -d+25, c,'z')
text(c, c,c-d+25,'y')

%% Loading Model 
load_model

set(gcf,'Visible','on')
param = get(gcf,'UserData');
param.xlim = get(gca,'XLim');
param.ylim = get(gca,'YLim');
param.zlim = get(gca,'ZLim');

% Add a camera light, and tone down the specular highlighting
camlight('headlight');
material('dull');

% Set a nice view angle
view([-135 35]);
axis manual off

%% Control panel
uipanel(...
        'Position',[0.01 0.01 0.22 0.98]);

%% Gantry panel
panel_gantry = uipanel(...
    'Title','Gantry angle',...
    'Tag','uipanel1',...
    'Position',[0.02 0.85 0.2 0.13]);

% alpha_gantry text
param.alpha_gantry_text = uicontrol(...
    'Parent',panel_gantry,...
    'Units','normalized',...
    'FontSize',10,...
    'Position',[0.08 0.54 0.2 0.3],...
    'String','< a',...
    'Style','text',...
    'Tag','text_alpha');

% alpha_gantry edit
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''string'');',...
    'set(param.alpha_gantry_slider,''value'',str2double(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];
param.alpha_gantry_edit = uicontrol(...
    'Parent',panel_gantry,...
    'Units','normalized',...
    'FontSize',8,...
    'Position',[0.28 0.54 0.64 0.3],...
    'String','0',...
    'Style','edit',...
    'Tag','edit_alpha',...
    'Callback',cbstring);

%alpha_gantry slider
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''value'');',...
    'set(param.alpha_gantry_edit,''string'',num2str(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];

param.alpha_gantry_slider = uicontrol(...
    'Parent',panel_gantry,...
    'Units','normalized',...
    'Position',[0.08 0.14 0.84 0.3],...
    'Value',0,...
    'Style','Slider',...
    'Min',0,...
    'Max',360,...
    'Callback',cbstring);

%% Couch angle panel
panel_couch_angle = uipanel(...
    'Title','Couch angle',...
    'Tag','uipanel1',...
    'Position',[0.02 0.72 0.2 0.13]);

% alpha_couch text
param.alpha_couch_text = uicontrol(...
    'Parent',panel_couch_angle,...
    'Units','normalized',...
    'FontSize',10,...
    'Position',[0.08 0.53 0.2 0.3],...
    'String','< b',...
    'Style','text',...
    'Tag','text_alpha');

% alpha_couch edit
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''string'');',...
    'set(param.alpha_couch_slider,''value'',str2double(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];
param.alpha_couch_edit = uicontrol(...
    'Parent',panel_couch_angle,...
    'Units','normalized',...
    'FontSize',8,...
    'Position',[0.28 0.54 0.64 0.3],...
    'String','0',...
    'Style','edit',...
    'Tag','edit_alpha',...
    'Callback',cbstring);

%alpha_couch slider
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''value'');',...
    'set(param.alpha_couch_edit,''string'',num2str(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];
param.alpha_couch_slider = uicontrol(...
    'Parent',panel_couch_angle,...
    'Units','normalized',...
    'Position',[0.08 0.14 0.84 0.3],...
    'Value',0,...
    'Style','Slider',...
    'Min',0,...
    'Max',360,...
    'Callback',cbstring);

%% Patient panel
panel_patient = uipanel(...
    'Title','Patient isocenter',...
    'Tag','uipanel1',...
    'Position',[0.02 0.42 0.2 0.30]);

% x_patient text
param.x_patient_text = uicontrol(...
    'Parent',panel_patient,...
    'Units','normalized',...
    'FontSize',10,...
    'Position',[0.08 0.86 0.2 0.12],...
    'String',' x',...
    'Style','text',...
    'Tag','text_x');

% x_Patient edit
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''string'');',...
    'set(param.x_patient_slider,''value'',str2double(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];
param.x_patient_edit = uicontrol(...
    'Parent',panel_patient,...
    'Units','normalized',...
    'FontSize',8,...
    'Position',[0.28 0.86 0.64 0.12],...
    'String','0',...
    'Style','edit',...
    'Tag','edit_x',...
    'Callback',cbstring);

%x_Patient slider
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''value'');',...
    'set(param.x_patient_edit,''string'',num2str(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];

param.x_patient_slider = uicontrol(...
    'Parent',panel_patient,...
    'Units','normalized',...
    'Position',[0.08 0.7 0.84 0.12],...
    'Value',0,...
    'Style','Slider',...
    'Min',-500,...
    'Max',500,...
    'Callback',cbstring);

% y_Patient text
param.y_patient_text = uicontrol(...
    'Parent',panel_patient,...
    'Units','normalized',...
    'FontSize',10,...
    'Position',[0.08 0.54 0.2 0.12],...
    'String',' y',...
    'Style','text',...
    'Tag','text_y');

% y_Patient edit
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''string'');',...
    'set(param.y_patient_slider,''value'',str2double(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];
param.y_patient_edit = uicontrol(...
    'Parent',panel_patient,...
    'Units','normalized',...
    'FontSize',8,...
    'Position',[0.28 0.54 0.64 0.12],...
    'String','0',...
    'Style','edit',...
    'Tag','edit_y',...
    'Callback',cbstring);

%y_Patient slider
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''value'');',...
    'set(param.y_patient_edit,''string'',num2str(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];

param.y_patient_slider = uicontrol(...
    'Parent',panel_patient,...
    'Units','normalized',...
    'Position',[0.08 0.38 0.84 0.12],...
    'Value',0.5,...
    'Style','Slider',...
    'Min',-1500,...
    'Max',1500,...
    'Callback',cbstring);
    
% z_Patient text
param.z_patient_text = uicontrol(...
    'Parent',panel_patient,...
    'Units','normalized',...
    'FontSize',10,...
    'Position',[0.08 0.2 0.2 0.12],...
    'String',' z',...
    'Style','text',...
    'Tag','text_z');

% z_Patient edit

cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''string'');',...
    'set(param.z_patient_slider,''value'',str2double(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];

param.z_patient_edit = uicontrol(...
    'Parent',panel_patient,...
    'Units','normalized',...
    'FontSize',8,...
    'Position',[0.28 0.2 0.64 0.12],...
    'String','0',...
    'Style','edit',...
    'Tag','edit_z',...
    'Callback',cbstring);

%z_Patient slider

cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''value'');',...
    'set(param.z_patient_edit,''string'',num2str(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];

param.z_patient_slider = uicontrol(...
    'Parent',panel_patient,...
    'Units','normalized',...
    'Position',[0.08 0.04 0.84 0.12],...
    'Value',0,...
    'Style','Slider',...
    'Min',-500,...
    'Max',500,...
    'Callback',cbstring);

%% Couch panel
panel_couch = uipanel(...
    'Title','Couch',...
    'Tag','uipanel1',...
    'Position',[0.02 0.23 0.2 0.18]);

% x_couch text
param.x_couch_text = uicontrol(...
    'Parent',panel_couch,...
    'Units','normalized',...
    'FontSize',10,...
    'Position',[0.08 0.76 0.2 0.2],...
    'String',' x',...
    'Style','text',...
    'Tag','text_x');

% x_Couch edit
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''string'');',...
    'set(param.x_couch_slider,''value'',str2double(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];

param.x_couch_edit = uicontrol(...
    'Parent',panel_couch,...
    'Units','normalized',...
    'FontSize',8,...
    'Position',[0.28 0.76 0.62 0.2],...
    'String','0',...
    'Style','edit',...
    'Tag','edit_x',...
    'Callback',cbstring);

%x_Couch slider
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''value'');',...
    'set(param.x_couch_edit,''string'',num2str(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];

param.x_couch_slider = uicontrol(...
    'Parent',panel_couch,...
    'Units','normalized',...
    'Position',[0.08 0.52 0.84 0.2],...
    'Value',0,...
    'Style','Slider',...
    'Min',-500,...
    'Max',500,...
    'Callback',cbstring);

% z_Couch text
param.z_couch_text = uicontrol(...
    'Parent',panel_couch,...
    'Units','normalized',...
    'FontSize',10,...
    'Position',[0.08 0.28 0.2 0.2],...
    'String',' z',...
    'Style','text',...
    'Tag','text_y');

% z_Couch edit
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''string'');',...
    'set(param.z_couch_slider,''value'',str2double(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];

param.z_couch_edit = uicontrol(...
    'Parent',panel_couch,...
    'Units','normalized',...
    'FontSize',8,...
    'Position',[0.28 0.28 0.64 0.2],...
    'String','0',...
    'Style','edit',...
    'Tag','edit_y',...
    'Callback',cbstring);

%z_Couch slider
cbstring = [...
    'param = get(gcf,''UserData'');',...
    's=get(gcbo,''value'');',...
    'set(param.z_couch_edit,''string'',num2str(s)),',...
    'set(gcf,''UserData'',param),',...
    'updt'];

param.z_couch_slider = uicontrol(...
    'Parent',panel_couch,...
    'Units','normalized',...
    'Position',[0.08 0.04 0.84 0.2],...
    'Value',0.5,...
    'Style','Slider',...
    'Min',-1500,...
    'Max',1500,...
    'Callback',cbstring);

%% Distance Button
param.distance_button = uicontrol(...
    'Tag','button',...
    'Style','Pushbutton',...
    'Units','normalized', ...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','DISTANCE',...
    'FontSize',12,...
    'FontWeight','bold',...
    'Position',[0.02 0.15 0.2 0.07],...
    'Callback','distance'); 

%% Traffic light
param.traffic_light = uicontrol(...
    'Tag','button',...
    'Style','Pushbutton',...
    'Units','normalized', ...
    'String','COLLISION RISK',...
    'FontWeight','bold',...
    'Position',[0.02 0.08 0.2 0.07],...
    'Callback',''); 

%% Reset Button
cbstring = [...
    'param = get(gcf,''UserData'');',...
    'set(param.alpha_gantry_edit,''string'',''0''),',...
    'set(param.alpha_gantry_slider,''value'',0),',...
    'set(param.alpha_couch_edit,''string'',''0''),',...
    'set(param.alpha_couch_slider,''value'',0),',...
    'set(param.x_couch_edit,''string'',''0''),',...
    'set(param.z_couch_edit,''string'',''0''),',...
    'set(param.x_couch_slider,''value'',0),',...
    'set(param.z_couch_slider,''value'',0),',...
    'set(param.x_patient_edit,''string'',''0''),',...
    'set(param.y_patient_edit,''string'',''0''),',...
    'set(param.z_patient_edit,''string'',''0''),',...
    'set(param.x_patient_slider,''value'',0),',...
    'set(param.y_patient_slider,''value'',0),',...
    'set(param.z_patient_slider,''value'',0),',...
    'set(gca,''view'',[-135 35]),',...
    'set(gca,''XLim'',param.xlim),',...
    'set(gca,''YLim'',param.ylim),',...
    'set(gca,''ZLim'',param.zlim),',...
    'set(gcf,''UserData'',param),',...
    'updt'];
param.resetbutton = uicontrol(...
    'Tag','button',...
    'Style','Pushbutton',...
    'Units','normalized', ...
    'String','RESET',...
    'FontSize',12,...
    'BackgroundColor',[0.8 0.8 0.8],...
    'Position',[0.02 0.01 0.2 0.07],...
    'Callback',cbstring); 

%% Minimum distance line
param.linedistPG = line([0,0],[0,0],[0,0],'color','red','linewidth',2);
param.textdistPG = text(0,0,0,'');

set(gcf,'UserData',param);

